services:
  macos_perf:
    image: dockurr/macos
    container_name: macos_perf
    environment:
      VERSION: "14"
      SIZE: "256G"   # Bigger primary drive
      QEMU_DISK_OPTS: "cache=writeback,discard=on,format=raw"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos_perf:/storage
    restart: always
    stop_grace_period: 2m
